<?php
namespace App\Service;

use App\Service\Tool\Genre as GenreTool;

class Genre extends GenreTool
{
    public function createEntity(string $entityClassName, array $parameters): object
    {
        $fields = [
            "name",
            "type"
        ];
        return $this->createSimpleEntity($entityClassName, $fields, $parameters); // TODO: Change the autogenerated stub
    }
}